### ISSUE TITLE
Unable to extract the archive

### ISSUE THREAD

**Issue by ExtremeYu** [trustsystems/elfinder-java-connector#2]
![qq 20160212013324](https://cloud.githubusercontent.com/assets/16620268/12984458/caac6fc4-d128-11e5-884f-d50c6867df6a.jpg)

**Comment by thiaguten** [comment]
Fixed in the commit https://github.com/trustsystems/elfinder-java-connector/commit/a6b03bd0f2c63658c3790ec4f8c79425e8d5fa3d
